### ISSUE TITLE
Occasional crashes when using faders

### ISSUE THREAD

**Issue by nohn** [solarnz/pamidicontrol#3]
Hardware is KORG nanoKONTROL2. pamidicontrol is running on an AMD based Ubuntu 22.04 Thinkpad:

Sometimes (I'd say twice a week during ~ 40 hours of use per week), pamidicontrol crashes when using the faders:

```
2023-04-18T09:33:18+02:00 INF Saw ControlChange input on Channel 0, Controller 0, with value 89
2023-04-18T09:33:18+02:00 INF Saw ControlChange input on Channel 0, Controller 0, with value 90
2023-04-18T09:33:19+02:00 INF Saw ControlChange input on Channel 0, Controller 0, with value 89
2023-04-18T09:33:19+02:00 INF Saw ControlChange input on Channel 0, Controller 0, with value 88
panic: Expected 1 volume entries, got 2.

goroutine 34 [running]:
github.com/solarnz/pamidicontrol/src.(*MidiClient).Run.func1(0x51857c?, {0x6fb600?, 0xc0001770c7?})
	/home/sebastian/Projects/pamidicontrol/src/midiclient.go:120 +0x310
gitlab.com/gomidi/midi/reader.(*Reader).dispatchMessage(0xc00013f8c0, {0x6fb600?, 0xc0001770c7?})
	/home/sebastian/Projects/pamidicontrol/vendor/gitlab.com/gomidi/midi/reader/message.go:237 +0x10c
gitlab.com/gomidi/midi/reader.(*Reader).dispatchMessageFromReader(0xc00013f8c0)
	/home/sebastian/Projects/pamidicontrol/vendor/gitlab.com/gomidi/midi/reader/reader.go:374 +0x55
gitlab.com/gomidi/midi/reader.(*inReader).handleMessage(0xc000126840, {0xc00017708b, 0x3, 0x3}, 0xa05de4e0)
	/home/sebastian/Projects/pamidicontrol/vendor/gitlab.com/gomidi/midi/reader/io.go:29 +0xb5
gitlab.com/gomidi/portmididrv.(*in).read(0xc000126700, 0xc000119ea0)
	/home/sebastian/Projects/pamidicontrol/vendor/gitlab.com/gomidi/portmididrv/in.go:108 +0xf7
gitlab.com/gomidi/portmididrv.(*in).SetListener(0xc000126700, 0xc000126858?)
	/home/sebastian/Projects/pamidicontrol/vendor/gitlab.com/gomidi/portmididrv/in.go:120 +0x7e
gitlab.com/gomidi/midi/reader.(*Reader).ListenTo(0xc00013f8c0, {0x6fcca8, 0xc000126700})
	/home/sebastian/Projects/pamidicontrol/vendor/gitlab.com/gomidi/midi/reader/io.go:78 +0x1b8
github.com/solarnz/pamidicontrol/src.(*MidiClient).Run(0xc000126640)
	/home/sebastian/Projects/pamidicontrol/src/midiclient.go:132 +0x2f7
created by github.com/solarnz/pamidicontrol/src.Run
	/home/sebastian/Projects/pamidicontrol/src/pamidicontrol.go:61 +0x672
```

**Comment by solarnz** [comment]
Hmmm, I suspect that might be coming from the midi libraries rather than `pamidicontrol` itself.
I've pushed a branch `2023-deps-update` that simply updates all of the dependencies, maybe that might help?

Unfortunately I haven't been able to test it, as I'm not sure where my nanoKONTROL2 went.

**Comment by nohn** [comment]
Hi @solarnz thanks. I've upgraded and keep you posted. Out of curiosity: Have you switched to a different solution or have you abandoned controlling PA with hardware devices?
